version: '3.8'

services:
  html-renderer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html-renderer-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    volumes:
      # Optional: Mount a volume for persistent sample files
      - ./samples:/app/samples:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/welcome"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s